
version: '3.8'
services:  
  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  backend:
    build:
      dockerfile: ./docker/backend/Dockerfile
      args:
        - PAT=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
    volumes:
      - /home/others/node/challenge-me/backend:/challenge-me/backend
    ports:
      - "4000:4000"  

     
  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      args:
        - PAT=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
    ports:
     - "3000:3000"
    volumes:
      - /home/others/node/challenge-me/frontend/app:/challenge-me/frontend/app



  

